//
//  imap-parse.c
//  imap-parse
//
//  Created by Patrick Rogers MC on 2019-07-24.
//
#include <libetpan/libetpan.h>
#include <stdlib.h>
#include <sys/stat.h>

#ifdef DEBUG
void mailimap_response_print(struct mailimap_response * resp);
void mailimap_greeting_print(struct mailimap_greeting * greeting);
#endif

static bool parse_corrupt_address(struct mailimap * imap)
{
  mailimap_set_malformed_address_workaround_enabled(imap, true);

  struct mailimap_response * response;
  int r;

  mmap_string_assign(imap->imap_stream_buffer,
    // Original corrupt response from the server
    "* 1012 FETCH (UID 11747 MODSEQ (389945790026418) FLAGS (\\Seen) ENVELOPE (\"Tue, 11 Jun 2019 05:54:41 -0400\" \"Re: info Sitges\" ((\"Keith Lindsay\" NIL \"keithlindsay\" \"me.com\")) ((\"Keith Lindsay\" NIL \"keithlindsay\" \"me.com\")) ((\"Keith Lindsay\" NIL \"keithlindsay\" \"me.com\")) ((NIL NIL \"=?utf-8?Q?\"Ruiz_Andr=C3=A9s\" NIL)(\"_Jorge_=40_Barcelona\\\"?=\" NIL \"jorge.ruiz\" \"cbrehotels.com\")) NIL NIL \"<DM6PR08MB4490B4481F1D8A6675159EA8E5ED0@DM6PR08MB4490.namprd08.prod.outlook.com>\" \"<9B3C4754-3C71-48B3-BEA9-28F6A6B7A5E9@me.com>\") BODYSTRUCTURE ((\"text\" \"plain\" (\"CHARSET\" \"utf-8\") NIL NIL \"quoted-printable\" 2411 74 NIL NIL NIL NIL)(\"text\" \"html\" (\"CHARSET\" \"utf-8\") NIL NIL \"quoted-printable\" 7559 214 NIL NIL NIL NIL) \"alternative\" (\"BOUNDARY\" \"Apple-Mail-BEF8D442-ACFA-43B5-8F82-5CC306AA99A2\") NIL NIL NIL) INTERNALDATE \"11-Jun-2019 09:54:42 +0000\" BODY[HEADER.FIELDS (References)] {2}\r\n" \
    "\r\n" \
    ")\r\n" \

    // Original corrupt response from the server, redacted
    "* 1012 FETCH (UID 11747 MODSEQ (389945790026418) FLAGS (\\Seen) ENVELOPE (\"Tue, 11 Jun 2019 05:54:41 -0400\" \"Subject Redacted\" ((\"From Redacted\" NIL \"from\" \"redacted.com\")) ((\"Sender Redacted\" NIL \"sender\" \"redacted.com\")) ((\"ReplyTo Redacted\" NIL \"reply\" \"redacted.com\")) ((NIL NIL \"=?utf-8?Q?\"To_Redacted=C3=A9s\" NIL)(\"_To_=40_Redacted\\\"?=\" NIL \"to.redacted\" \"example.com\")) NIL NIL \"<DM6PR_REDACTEDHASH.namprd08.prod.outlook.com>\" \"<9B3C4754-REDACTED-HASH@me.com>\") BODYSTRUCTURE ((\"text\" \"plain\" (\"CHARSET\" \"utf-8\") NIL NIL \"quoted-printable\" 2411 74 NIL NIL NIL NIL)(\"text\" \"html\" (\"CHARSET\" \"utf-8\") NIL NIL \"quoted-printable\" 7559 214 NIL NIL NIL NIL) \"alternative\" (\"BOUNDARY\" \"Apple-Mail-BEF8D442-ACFA-43B5-8F82-5CC306AA99A2\") NIL NIL NIL) INTERNALDATE \"11-Jun-2019 09:54:42 +0000\" BODY[HEADER.FIELDS (References)] {2}\r\n" \
    "\r\n" \
    ")\r\n" \

    // Pruned/redacted corrupt response
    "* 1013 FETCH (ENVELOPE (\"Tue, 11 Jun 2019 05:54:41 -0400\" \"Subject Redacted\" NIL NIL NIL ((NIL NIL \"=?utf-8?Q?\"John_Doe=C3=A9s\" NIL)(\"_John_=40_Doe\\\"?=\" NIL \"other.recipient\" \"example.com\")) NIL NIL NIL NIL))\r\n" \

    // Response without corrupt address
    "* 1014 FETCH (ENVELOPE (\"Tue, 11 Jun 2019 05:54:41 -0400\" \"Subject Redacted\" NIL NIL NIL ((\"_John_=40_Doe\\\"?=\" NIL \"other.recipient\" \"example.com\")) NIL NIL NIL NIL))\r\n" \

    // Test a basic synthetic address
    "* 1015 FETCH (ENVELOPE (NIL NIL NIL NIL NIL ((\"personal\" \"domain\" \"mailbox\" \"host\")) NIL NIL NIL NIL))\r\n" \

    // Test all cases when an address contains a quote
    "* 1016 FETCH (ENVELOPE (NIL NIL NIL NIL NIL ((\"pers\"onal\" \"dom\"ain\" \"mailb\"ox\" \"ho\"st\")) NIL NIL NIL NIL))\r\n" \

    // Test when two address strings are adjacent (no space)
//    "* 1017 FETCH (ENVELOPE (NIL NIL NIL NIL NIL ((\"personal\"\"domain\" NIL NIL)) NIL NIL NIL NIL))\r\n" \

    // Valid response from my acount, generated by the following query:
    // 75 UID FETCH 551 (UID FLAGS X-GM-LABELS X-GM-THRID X-GM-MSGID ENVELOPE BODYSTRUCTURE INTERNALDATE BODY.PEEK[HEADER.FIELDS (References)])
    "* 181 FETCH (X-GM-THRID 1639978641668081211 X-GM-MSGID 1639978641668081211 X-GM-LABELS (\"\\Important\") UID 551 MODSEQ (375530) INTERNALDATE \"24-Jul-2019 21:58:30 +0000\" FLAGS () ENVELOPE (\"Wed, 24 Jul 2019 17:58:34 -0400\" \"Ping\" ((\"Patrick Rogers\" NIL \"progers\" \"marketcircle.com\")) ((\"Patrick Rogers\" NIL \"progers\" \"marketcircle.com\")) ((\"Patrick Rogers\" NIL \"progers\" \"marketcircle.com\")) ((\"Edna Worthington\" NIL \"imip.test\" \"gmail.com\")) NIL NIL NIL \"<02111445-AE9F-4642-9E86-D802512EC904@marketcircle.com>\") BODYSTRUCTURE ((\"TEXT\" \"PLAIN\" (\"CHARSET\" \"us-ascii\") NIL NIL \"7BIT\" 4 1 NIL NIL NIL)(\"APPLICATION\" \"PKCS7-SIGNATURE\" (\"NAME\" \"smime.p7s\") NIL NIL \"BASE64\" 5328 NIL (\"ATTACHMENT\" (\"FILENAME\" \"smime.p7s\")) NIL) \"SIGNED\" (\"BOUNDARY\" \"Apple-Mail=_2C80CFB4-2B58-4489-9EC8-9478223CE9DE\" \"MICALG\" \"sha-256\" \"PROTOCOL\" \"application/pkcs7-signature\") NIL NIL) BODY[HEADER.FIELDS (References)] {2}\r\n" \
    "\r\n" \
    ")\r\n" \

    "72 OK Success\r\n"
  );
  imap->imap_tag = 72;

  r = mailimap_parse_response(imap, &response);
  mailimap_set_malformed_address_workaround_enabled(imap, false);

  if (r == MAILIMAP_NO_ERROR) {
#ifdef DEBUG
    mailimap_response_print(response);
#endif
    mailimap_response_free(response);
    return(true);
  } else {
    fprintf(stderr, "Could not parse IMAP response, got error %d\n", r);
    return(false);
  }
}

static bool parse_truncated_corrupt_address(struct mailimap * imap)
{
  mailimap_set_malformed_address_workaround_enabled(imap, true);

  struct mailimap_response * response;
  int r;

  mmap_string_assign(imap->imap_stream_buffer,
    // The mailbox is truncated following the quote for mailbox
    "* 1015 FETCH (ENVELOPE (NIL NIL NIL NIL NIL ((\"personal\" \"domain\" \"mailbox\"" \
  );
  imap->imap_tag = 72;

  r = mailimap_parse_response(imap, &response);
  mailimap_set_malformed_address_workaround_enabled(imap, false);

  if (r == MAILIMAP_NO_ERROR) {
    fprintf(stderr, "Received unexpected success when there was no complete data to process\n");

#ifdef DEBUG
    mailimap_response_print(response);
#endif
    mailimap_response_free(response);
  }
  
  if (r == MAILIMAP_ERROR_NEEDS_MORE_DATA) {
      return(true);
  } else {
    fprintf(stderr, "Parsing should have failed with needs more data error, instead got: %d\n", r);
    return(false);
  }
}

static bool parse_corrupt_subject(struct mailimap * imap)
{
  mailimap_set_malformed_address_workaround_enabled(imap, true);

  struct mailimap_response * response;
  int r;

  mmap_string_assign(imap->imap_stream_buffer,
    // The subject contains a DQuote. This should not be 'fixed' by the hack.
    "* 1015 FETCH (ENVELOPE (NIL \"Subject\"With An Internal DQuote\" NIL NIL NIL ((\"personal\" \"domain\" \"mailbox\" \"host\")) NIL NIL NIL NIL))\r\n" \
  );
  imap->imap_tag = 72;

  r = mailimap_parse_response(imap, &response);
  mailimap_set_malformed_address_workaround_enabled(imap, false);

  if (r == MAILIMAP_NO_ERROR) {
    fprintf(stderr, "Received unexpected success when parsing a subject with an internal quote. This should fail since the 'fix' only applies to addressses\n");

#ifdef DEBUG
    mailimap_response_print(response);
#endif
    mailimap_response_free(response);
    
    return(false);
  } else {
    return(true);
  }
}

static bool parse_corrupt_hack_disabled(struct mailimap * imap)
{
  struct mailimap_response * response;
  int r;

  mmap_string_assign(imap->imap_stream_buffer,
    // Since the malformed address workaround is disabled these should not be parsed correctly (same test string as above).
    "* 1016 FETCH (ENVELOPE (NIL NIL NIL NIL NIL ((\"pers\"onal\" \"dom\"ain\" \"mailb\"ox\" \"ho\"st\")) NIL NIL NIL NIL))\r\n" \
  );
  imap->imap_tag = 72;

  r = mailimap_parse_response(imap, &response);

  if (r == MAILIMAP_NO_ERROR) {
    fprintf(stderr, "Received unexpected success when parsing a corrupt address with the parser hack disabled\n");

#ifdef DEBUG
    mailimap_response_print(response);
#endif
    mailimap_response_free(response);
    
    return(false);
  } else if (r != MAILIMAP_ERROR_PARSE) {
    fprintf(stderr, "Received unexpected failure when parsing a corrupt address with the parser hack disabled. Parsing should have failed, but with a parse error. Instead received error %d\n", r);
    return(false);
  } else {
    return(true);
  }
}

int main(int argc, char ** argv)
{
  struct mailimap * imap;
  bool success = true;
  
  imap = mailimap_new(0, NULL);
  
  success &= parse_corrupt_address(imap);
  success &= parse_truncated_corrupt_address(imap);
  success &= parse_corrupt_subject(imap);
  success &= parse_corrupt_hack_disabled(imap);

  mailimap_free(imap);
  
  exit(success ? EXIT_SUCCESS : EXIT_FAILURE);
}
